services:
  - type: web
    name: c3-notes-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /api/health/
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: c3-notes-api.onrender.com
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: c3-notes-db
          property: connectionString

databases:
  - name: c3-notes-db
    plan: free
