services:
  - type: web
    name: simple-notes-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: simple-notes-api.onrender.com
